#!/bin/bash 
#: Title        : backup-script
#: Date         : Nov 20, 2022
#: Authors      : Liam Brooke, Karl Cue
#: Version      : 1.0
#: Description  : Backs up to the specified location.

source "./config"

for i in "${#BACKUP_DIRS[@]}"
do
    if [ -d "$i" ]
    then
        rsync -aPv $i "$BACKUP_IP:$BACKUP_LOCATION"
    else
        echo "Cannot find directory $i."
    fi
done

echo "Done backing up."